---
#- hosts: "{{ groups['mirror']|first }}"
#  connection: local
#  gather_facts: no
#  tasks:
#    - include_role:
#        name: ovh
#      when: "'dev' in inventory_hostname"
#      delegate_to: localhost
- hosts: mirror
  remote_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  tasks:
    - name: install software
      apt:
        name: "{{item }}"
        state: present
      with_items:
        - rsync
        - ubumirror
        - iftop
        - sendmail
    - name: Copy ssh keys
      authorized_key:
        user: root
        state: present
        key: "{{ public_key }}"
    - name: Create mirror user
      user:
        name: mirror
        state: present
    - name: Create webroot directories
      file: 
        path: "{{ nginx_root }}"
        state: directory
        owner: mirror
        group: mirror
        mode: 0775
    - name: Create directories
      file: 
        path: "{{ item }}"
        state: directory
        mode: 0775
      with_items:
        - /var/log/ubumirror
        - "{{ nginx_root }}ubuntu-archive/"
        - "{{ nginx_root }}ubuntu-release/"
    - name: Create ubumirror conf
      template: 
        dest: "/etc/ubumirror.conf"
        src: etc/ubumirror.conf.j2
        mode: 0775
    - name: Execute sync script
      command: "{{ item }}"
      args:
        creates: "{{ nginx_root }}/ubuntu-release/robots.txt"
      with_items:
        - ubuarchive
        - uburelease
    - name: create cron entry
      cron:
        name: "{{ item }}"
        minute: "7"
        hour: "*/1"
        job: " {{ item }}° /dev/null"
        user: mirror
      with_items:
        - /usr/bin/ubuarchive
        - /usr/bin/uburelease
   
- hosts: mirror
  remote_user: root
  roles:
    - { role: ansible-role-nginx, nginx_user: mirror }
