---
- hosts: "{{ groups['mirror']|first }}"
  connection: local
  gather_facts: no
  tasks:
    - include_role:
        name: ovh
      when: "'dev' in inventory_hostname"
      delegate_to: localhost
- hosts: mirror
  remote_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - { role: ansible-role-nginx, nginx_user: mirror }
  tasks:
    - name: install rsync
      apt:
        name: rsync
        state: present
    - name: Copy ssh keys
      authorized_key:
        user: root
        state: present
        key: "{{ public_key }}"
    - name: Create mirror user
      user:
        name: mirror
        state: present
    - name: Create webroot directories
      file: 
        path: "{{ nginx_root }}"
        state: directory
        owner: mirror
        group: mirror
        mode: 0775
    - name: Copy sync files
      template:
        src: "{{ item }}.j2"
        dest: ~mirror/{{ item }}
        mode: 0755
        owner: mirror
        group: mirror
      with_items:
        - sync_archive.sh
        - sync_cd.sh
    - name: Execute sync script
      command: ~mirror/{{ item }}
      args:
        creates: "{{ nginx_root }}/ubuntu-release/robots.txt"
      with_items:
        - sync_archive.sh
        - sync_cd.sh
    - name: create cron entry
      cron:
        name: "{{ item }}"
        minute: "7"
        hour: "*/4"
        job: " ~mirror/{{ item }}> /dev/null"
        user: mirror
      with_items:
        - sync_archive.sh
        - sync_cd.sh
   
