---
- hosts: mirror
  remote_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - role: ansible-nginx
  tasks:
    - name: Copy ssh keys
      authorized_key:
        user: root
        state: present
        key: "{{ public_key }}"
    - name: Create mirror user
      user:
        name: mirror
        state: present
    - name: Create webroot directories
      file: 
        path: "{{ item.value.root }}"
        state: directory
        owner: mirror
        group: mirror
        mode: 0775
      with_dict: "{{ nginx_sites }}"
    - name: Copy sync file
      copy:
        src: sync_mirror.sh
        dest: ~mirror/sync_mirror.sh
        mode: 0755
        owner: mirror
        group: mirror
    - name: Execute sync script
      command: ~mirror/sync_mirror.sh
      args:
        creates: /home/mirror/www/mirror.tuxcall.de/ubuntu/robots.txt
    - name: create cron entry
      cron:
        name: "mirror sync"
        minute: "7"
        hour: "*/4"
        job: " ~mirror/sync_mirror.sh> /dev/null"
        user: mirror
   
