---
nginx_root: /var/www/{{ inventory_hostname }}/
nginx_sites:
 default:
     - listen 80
     - listen [::]80
     - server_name {{ inventory_hostname }}
     - root "{{ nginx_root }}"
     - autoindex on
 de.releases.ubuntu.com:
     - listen 80
     - listen [::]80
     - server_name de.releases.ubuntu.com
     - root "{{ nginx_root }}ubuntu-release"
     - autoindex on
 de.archive.ubuntu.com:
     - listen 80
     - listen [::]80
     - server_name de.archive.ubuntu.com
     - root "{{ nginx_root }}ubuntu-archive"
     - autoindex on
