---
nginx_root: /home/mirror/www/{{ inventory_hostname }}/
nginx_sites:
 default:
     - listen 80
     - listen [::]80
     - server_name {{ inventory_hostname }}
     - root "{{ nginx_root }}"
     - autoindex on
  tuxcall.de:
     - listen 80
     - listen [::]80
     - server_name de.releases.ubuntu.com
     - root "{{ nginx_root }}ubuntu-release"
     - autoindex on
